### ISSUE TITLE
How I can install it properly?

### ISSUE THREAD

**Issue by ReydVires** [MCluck90/cordova-plugin-android-volume#11]
The title is the major question. After install on npm, and try to call the API of `window.androidVolume`, its still undefined.

Thanks.

**Comment by ReydVires** [comment]
Oh sorry, its fixed with this:
`$ cordova plugin add https://github.com/MCluck90/cordova-plugin-android-volume.git`

**Comment by mikecluck** [comment]
Glad you got it figured out!

**Comment by ReydVires** [comment]
Thank for your nice plugin!
And my advice is maybe you need to explicit to write that installing step.
