### ISSUE TITLE
showToast is not working...

### ISSUE THREAD

**Issue by codingDSR** [MCluck90/cordova-plugin-android-volume#2]
boolean false value for showToast parameter still displays Toast.

**Comment by mikecluck** [comment]
You'll have to show me some sample code that produces the issue.

As far as I can tell [that's impossible.](https://github.com/MCluck90/cordova-plugin-android-volume/blob/master/src/android/com/mcluck/plugin/AndroidVolume.java#L63)

**Comment by OnfireNFS** [comment]
I had the same issue of the toast still being displayed while using this code.
`window.androidVolume.setNotification(100, false);`

I tried this code and it fixed the issue.
`window.androidVolume.setNotification(100, false, null, null);`

Hopefully this information helps.

**Comment by mikecluck** [comment]
Huh, that's strange. I literally don't know why that would change anything.

**Comment by OnfireNFS** [comment]
Yeah. I just switched my code back to `window.androidVolume.setNotification(100, false);` to make sure I'm not crazy and that does seem to cause the issue. Maybe it is something to do with only having 2 parameters.

Either way hopefully anyone else who has this issue will see that they can fix it by just setting the callbacks to null. 

Awesome plugin by the way. No idea what I would do without it!
