### ISSUE TITLE
window.androidVolume.setMusic(f,false); still give a toast

### ISSUE THREAD

**Issue by luigi37** [MCluck90/cordova-plugin-android-volume#4]
As per title... it seems the toast is anyway issued...

**Comment by mikecluck** [comment]
That's so strange. [Someone posted about that before](https://github.com/MCluck90/cordova-plugin-android-volume/issues/2) and I'm still confused as to why that's the case. I'll try to look into it sometime soon.

**Comment by luigi37** [comment]
Mike give a look at js setvolume.
It seems if parameters are less than 4 you have set toast to true...

**Comment by luigi37** [comment]
That would explain other user's post behaviour

**Comment by mikecluck** [comment]
Oh yeah, I guess so. I remember doing that now. The thinking was that it would default to showing it because this originally was just meant for me as part of a weekend project. That'll be an easy fix to make.

**Comment by luigi37** [comment]
Cool, thanks :-)
