### ISSUE TITLE
cannot find module cordova/exec IONIC 3

### ISSUE THREAD

**Issue by maykoestevez** [MCluck90/cordova-plugin-android-volume#7]
Hello,

Thanks for this plugin, is very helpful.

Im getting this error while running  this code

`import androidVolume from 'cordova-plugin-android-volume/www/AndroidVolume'
`

When platform ready
```
 platform.ready().then(() => {

      androidVolume.getMusic((volume) => {
        console.log('valumen =>' +volume);

      }, (error) => {

        console.log('error=>' +error);
      });



    });
```

Cordova verision 
8.1.2 (cordova-lib@8.1.1)

**Comment by mikecluck** [comment]
I can't say that I've seen that error before. Did you install the plugin via `devDependencies`? [One person had the same problem as you](https://github.com/ionic-team/capacitor/issues/1032) and that seemed to be the problem.

**Comment by maykoestevez** [comment]
I checked in my package.json the plugin is installed under "dependencies" 

```
{
  "name": "test",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/android-exoplayer": "^4.14.0",
    "@ionic-native/app-availability": "^4.12.2",
    "@ionic-native/core": "~4.12.0",
    "@ionic-native/device": "^4.19.0",
    "@ionic-native/file": "^4.14.0",
    "@ionic-native/file-transfer": "^4.14.0",
    "@ionic-native/in-app-browser": "^4.12.2",
    "@ionic-native/paypal": "^4.18.0",
    "@ionic-native/screen-orientation": "^4.19.0",
    "@ionic-native/splash-screen": "~4.12.0",
    "@ionic-native/status-bar": "~4.12.0",
    "@ionic-native/streaming-media": "^4.12.1",
    "@ionic/storage": "^2.1.3",
    "@types/jquery": "^3.3.29",
    "braintree-web": "^3.41.0",
    "card.io.cordova.mobilesdk": "^2.1.0",
    "com.hughisaacs2.cordova.plugins.androidtvplugin": "git+https://github.com/hughisaacs2/Cordova-Android-TV-Plugin.git",
    "com.lampa.startapp": "^6.1.6",
    "com.paypal.cordova.mobilesdk": "^3.5.0",
    "cordova-android": "7.1.4",
    **"cordova-plugin-android-volume": "0.0.12",**
    "cordova-plugin-appavailability": "^0.4.2",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-exoplayer": "^2.5.4",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-screen-orientation": "3.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-streaming-media": "^2.1.3",
    "cordova-plugin-volume-control": "0.1.9",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.5.2",
    "es6-promise-plugin": "4.2.2",
    "fm.radiant.cordova.utils.volume": "^0.1.0",
    "gulp": "^3.9.1",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "jquery": "^3.3.1",
    "moment": "^2.23.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.0",
    "@ionic/lab": "1.0.8",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-streaming-media": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-appavailability": {},
      "com.lampa.startapp": {},
      "cordova-plugin-exoplayer": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file": {},
      "com.hughisaacs2.cordova.plugins.androidtvplugin": {},
      "com.paypal.cordova.mobilesdk": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-volume-control": {}
    },
    "platforms": [
      "android"
    ]
  }
}
```

**Comment by mikecluck** [comment]
Have you tried loading the module with the recommended syntax?

```js
const androidVolume = require('cordova-plugin-android-volume/www/AndroidVolume.js')
```

I never used Ionic so I don't know if the dependency resolution system works any different than just Cordova.

**Comment by steveshp** [comment]
declare var androidVolume: any;
and 
androidVolume.setSystem(80);

**Comment by maykoestevez** [comment]
Hi, thanks @steveshp  for you help,

I tried this and i get AndroidVolume is not defined 
```
declare var androidVolume: any;
androidVolume.setSystem(80); 
```

**Comment by steveshp** [comment]
This is my code

import { Component } from '@angular/core';
import { IonicPage, NavController, Platform, MenuController } from 'ionic-angular';
import { AppMinimize } from '@ionic-native/app-minimize';
import { BackgroundMode } from '@ionic-native/background-mode';
import * as moment from 'moment';
// import {localStoreSound} from '../../app/app.module';
import { Media, MediaObject } from '@ionic-native/media';
import { Storage } from '@ionic/storage';
import { AngularFireAuth } from 'angularfire2/auth';
import * as firebase from 'firebase/app';
import { AngularFireDatabase, FirebaseObjectObservable} from 'angularfire2/database-deprecated';
import { AuthData } from '../../providers/auth-data';
import md5 from 'crypto-md5'; // dependencies:"crypto-md5"


declare var androidVolume: any;

@IonicPage()
@Component({
  selector: 'page-mainplay',
  templateUrl: 'mainplay.html',
})
export class MainplayPage {
  playorstop: string = "ios-volume-off";
  statusText: string;
  colorSetup: string = "mij"
  toggleVal: number = 1;

  private tinnitus: MediaObject;
  public fileplay: any;


  private NST500AMBBN: string;
  private TRTAMBBN  : string;
  private CURRENTVOLUME : number;
  private soundName: string;
  public displayIcon: number = 0;

  email: any;
  profilePicture: any = "https://www.gravatar.com/avatar/"
  profileArray : any=[]; 
  profile: FirebaseObjectObservable<any[]>;
  uid:any;
  name: string;


  constructor(public navCtrl: NavController, private appMinimize: AppMinimize, private plt: Platform, private backgroundMode: BackgroundMode
    , private media:Media, private storage: Storage, public afAuth: AngularFireAuth
    , public authData: AuthData,public afDb: AngularFireDatabase, private menuController: MenuController) {
    this.plt.registerBackButtonAction(() => {
      this.appMinimize.minimize();
    });
    this.backgroundMode.enable();
   
  }

 ionViewWillEnter() {
    this.menuController.swipeEnable(false);
    this.storage.get('CURRENTVOLUME').then((val) => {
      this.CURRENTVOLUME = val;
    });
    androidVolume.setMusic(this.CURRENTVOLUME);
 }

**Comment by maykoestevez** [comment]
Thanks for your help @MCluck90 , @steveshp 

My problem was the installation 
I runned this commad 
`npm i cordova-plugin-android-volume`

But I did not add the crodova plugin like this 
`cordova plugin add <path to plugin folder>`

After i ran this commad everything worked well.
